site_name: cerisse++
docs_dir: docs
nav:
  - Home: README.md
  - Quick: quickstart.md
  - Tutorial: tutorial.md
  - Tips: tips.md
  - Setup: setup.md
  - Prob: prob.md
  - Input: input.md
  - Make: makefile.md
  - Theory: equations.md
extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.4/MathJax.js?config=TeX-AMS-MML_HTMLorMML
markdown_extensions:
  - mdx_math
  - callouts
  - footnotes
  - pymdownx.magiclink
  - pymdownx.snippets:
      check_paths: true

