site_name: cerisse++
docs_dir: docs
nav:
  - Home: README.md
  - Quick: quickstart.md
markdown_extensions:
  - mdx_math
  - callouts
  - footnotes
  - pymdownx.magiclink
  - pymdownx.snippets:
      check_paths: true

