site_name: cerisse
nav:
  - Home: index.md
  - Quickrun: quickrun.md
  - Run: run.md
  - LES: les.md
  - PDF: pdf.md
  - Examples: example.md
  - Input options: input-options.md
  - Tips: tips.md   
  - Test: test.md
extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.4/MathJax.js?config=TeX-AMS-MML_HTMLorMML
markdown_extensions:
  - mdx_math
  - callouts
  - footnotes
  - pymdownx.magiclink
  - pymdownx.snippets:
      check_paths: true

