site_name: cerisse++
docs_dir: doc_new
nav:
  - Home: index.md
  - input: input-options.md
  - NEW: new_run.md
  - CLASS: new_class.md
  - QuickStart: Quickrun
  - Tests: new_test.md
  - IBM: ibm.md
extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.4/MathJax.js?config=TeX-AMS-MML_HTMLorMML
markdown_extensions:
  - mdx_math
  - callouts
  - footnotes
  - pymdownx.magiclink
  - pymdownx.snippets:
      check_paths: true

