site_name: cerisse++
docs_dir: doc_new
nav:
  - Home: index.md
  - Quick: quickrun.md
  - input: input-options.md
  - Run: new_run.md
  - Class: new_class.md
  - Tests: new_test.md
  - IBM: ibm.md
  - Tutorial: tutorial.md
  - tips: tips.md  
  - errors: errors.md
extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.4/MathJax.js?config=TeX-AMS-MML_HTMLorMML
markdown_extensions:
  - mdx_math
  - callouts
  - footnotes
  - pymdownx.magiclink
  - pymdownx.snippets:
      check_paths: true

