site_name: cerisse++
docs_dir: docs
nav:
   - Home: README.md
   - Getting Started:
      - QuickStart: quickstart.md
      - Tutorial: tutorial.md
      - Tips: tips.md
   - SETUP:
      - Overview: setup.md
      - PROB: prob.md
      - Input: input.md
      - Make: makefile.md
      - BC: bc.md
      - CHEM: chemistry.md
      - Analysis: analysis.md
   - EXAMPLES:
      - Examples: examples.md
      - OneDim: onedim.md
      - TwoDim: twodim.md
      - ThreeDim: threedim.md
   - THEORY:
      - Equations: equations.md
      - DNS: theory/equations/dns.md
      - LES: theory/equations/les.md
      - TurbComb: theory/equations/turbcomb.md
      - Numerics: theory/equations/numerical-methods.md
      - Geometry: theory/ibmeb.md
   - CODE:
      - structure: code.md
      - index: indexvar.md
      - solver: fluxsolver.md
      - thermo: thermosolver.md
extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.4/MathJax.js?config=TeX-AMS-MML_HTMLorMML
markdown_extensions:
  - mdx_math
  - callouts
  - footnotes
  - pymdownx.magiclink
  - pymdownx.snippets:
      check_paths: true

