# ====================================================== #
#                  CERISSE INPUT SCRIPT                  #
# ====================================================== #
# TGV vortex input file to test output
max_step = 100000
stop_time = 0.0018336339443081453
#stop_time = 0.00014669261631858238 # M=1.25

# ================ COMPUTATIONAL DOMAIN ================ #
geometry.is_periodic = 1 1 1
geometry.coord_sys   = 0  # 0 => cart, 1 => RZ  2=>spherical
geometry.prob_lo     = -1.0 -1.0 -1.0
geometry.prob_hi     =  1.0  1.0  1.0
# use with single level
amr.n_cell           =  128    128    128
eb2.geom_type = all_regular

# ================ BOUNDARY CONDITIONS ================= #
# 0 = Interior             3 = Symmetry
# 1 = Inflow / UserBC      4 = SlipWall = 3
# 2 = Outflow (FOExtrap)   5 = NoSlipWall (adiabatic)
cns.lo_bc = 0 0 0
cns.hi_bc = 0 0 0

# ==================== WHAT PHYSICS ==================== #
#cns.do_hydro = 1
cns.do_visc  = 1

# ==================== WHAT NUMERICS =================== #
cns.cfl = 0.3
cns.dt_cutoff = 5.e-20
cns.recon_scheme = 6   #  TENO
cns.do_vpdf      = 1   # enable Lagevin model and p_sgs correction
cns.do_spdf      = 0   # enable IEM model
cns.clip_temp    = 0   # clip minimum temperature [K]

# ================== REACTION SETTINGS ================= #
cns.do_react = 0

# ================ VERBOSITY & DIAGNOSIS =============== #
cns.v = 2 # 0/1/2
amr.v = 1
ode.verbose = 0
amr.data_log = tgv128.log
# ==================== LOAD BALANCE ==================== #
amr.loadbalance_with_workestimates = 1 # for multi-level run, loadbalance_int = regrid_int
amr.loadbalance_level0_int = 1000     # for single level run (amr.max_level = 0) only

# =============== REFINEMENT / REGRIDDING ============== #
amr.max_level       = 0       # maximum level number allowed
amr.ref_ratio       = 2 2 2 2 # refinement ratio
amr.regrid_int      = 5       # how often to regrid
amr.blocking_factor = 8
amr.max_grid_size   = 64
amr.n_error_buf     = 2 2 2 2 # number of buffer cells in error est
amr.grid_eff        = 0.7

# ==================== OUTPUT FILES ==================== #
amr.checkpoint_files_output = 0
amr.check_file      = chk    # root name of checkpoint file
amr.check_int       = 1000   # number of timesteps between checkpoints

amr.plot_files_output = 1
amr.plot_file         = plot/plt # root name of plotfile
amr.plot_int          = 200  # number of timesteps between plotfiles
amr.derive_plot_vars  = pressure velocity magvort transport_coef reynolds_stress #temp MachNumber divrho divu cv cp 
cns.plot_rhoy = 0
cns.plot_molefrac = 0
cns.plot_massfrac = 0

# ================= PROBLEM PARAMETERS ================= #
prob.reynolds = 1600.0
prob.mach = 0.1
#prob.mach = 1.25
prob.prandtl = 0.71
