#!/bin/bash   
##SBATCH --mail-type=ALL
#SBATCH --mail-user=mpatel38@umd.edu
#SBATCH --output=slurm-%j.out
#SBATCH --error=slurm-%j.err
#SBATCH -A brehm-prj-paid
#SBATCH -t 00-00:10:00
#SBATCH -n 1 
#SBATCH -c 1 
#SBATCH --gpus=a100:1
#SBATCH -p gpu

source ~/.bashrc

module load gcc/11.3.0
module load openmpi/gcc/11.3.0
module load cuda/11.8.0

./main3d.gnu.CUDA.ex inputs 
