TINY_PROFILE 	= FALSE
DEBUG   	= FALSE
PRECISION       = DOUBLE # DOUBLE or FLOAT
DIM     	= 3
COMP 		= gcc
CXXSTD          = c++17 # c++17 default
USE_CUDA 	= FALSE
USE_MPI 	= FALSE
USE_OMP 	= FALSE
USE_GPIBM	= FALSE
AMREX_NO_PROBINIT =TRUE

include ./Make.package
include $(AMR_SOLVER)/src/Make.CNS
