from datetime import datetime
from sympy import symbols, sin, cos, pi, Rational, simplify, lambdify, cxxcode

# Set up MMS exact solution
x_a, y_a, z_a, gamma, mu, muk, k = symbols("x y z gamma mu muk k")  # k = lambda / cv
rho_a = 1 + sin(2 * pi * x_a) / 5
u_a = sin(3 * pi * x_a) * cos(1 * pi * z_a)
v_a = cos(2 * pi * y_a) * sin(1 * pi * z_a)
w_a = 0 * z_a
p_a = 1 - sin(1 * pi * x_a) * cos(1 * pi * y_a) / 4
ret_a = p_a / (gamma - 1) + rho_a * (u_a**2 + v_a**2 + w_a**2) / 2

# Hydro source terms
hsrc_a = [
  simplify(
      (rho_a * u_a).diff(x_a) + (rho_a * v_a).diff(y_a) + (rho_a * w_a).diff(z_a)
  ),
  simplify(
      (rho_a * u_a**2 + p_a).diff(x_a)
      + (rho_a * u_a * v_a).diff(y_a)
      + (rho_a * u_a * w_a).diff(z_a)
  ),
  simplify(
      (rho_a * u_a * v_a).diff(x_a)
      + (rho_a * v_a**2 + p_a).diff(y_a)
      + (rho_a * v_a * w_a).diff(z_a)
  ),
  simplify(
      (rho_a * u_a * w_a).diff(x_a)
      + (rho_a * v_a * w_a).diff(y_a)
      + (rho_a * w_a**2 + p_a).diff(z_a)
  ),
  simplify(
      ((ret_a + p_a) * u_a).diff(x_a)
      + ((ret_a + p_a) * v_a).diff(y_a)
      + ((ret_a + p_a) * w_a).diff(z_a)
  ),
]

# Visc source terms
divu = simplify(u_a.diff(x_a) + v_a.diff(y_a) + w_a.diff(z_a))
tauxx = mu * simplify(2 * u_a.diff(x_a) - Rational(2, 3) * divu) + muk * divu
tauxy = mu * simplify(u_a.diff(y_a) + v_a.diff(x_a))
tauxz = mu * simplify(u_a.diff(z_a) + w_a.diff(x_a))
tauyy = mu * simplify(2 * v_a.diff(y_a) - Rational(2, 3) * divu) + muk * divu
tauyz = mu * simplify(v_a.diff(z_a) + w_a.diff(y_a))
tauzz = mu * simplify(2 * w_a.diff(z_a) - Rational(2, 3) * divu) + muk * divu
ei_a = p_a / (gamma - 1) / rho_a

vsrc_a = [
  0,
  simplify(-tauxx.diff(x_a) - tauxy.diff(y_a) - tauxz.diff(z_a)),
  simplify(-tauxy.diff(x_a) - tauyy.diff(y_a) - tauyz.diff(z_a)),
  simplify(-tauxz.diff(x_a) - tauyz.diff(y_a) - tauzz.diff(z_a)),
  simplify(
      -(tauxx * u_a + tauxy * v_a + tauxz * w_a).diff(x_a)
      - (tauxy * u_a + tauyy * v_a + tauyz * w_a).diff(y_a)
      - (tauxz * u_a + tauyz * v_a + tauzz * w_a).diff(z_a)
      - k * (ei_a.diff(x_a) + ei_a.diff(y_a) + ei_a.diff(z_a))
  ),
]

# Write C++ header
hpp_content = f"""// This file is automatically generated
// Last update: {datetime.now().strftime("%d/%m/%Y %H:%M:%S")}
#ifndef MMS_HPP
#define MMS_HPP

#include <cmath>
#include <AMReX_REAL.H>
#include <PelePhysics.H>

namespace mms {{
constexpr amrex::Real gamma = pele::physics::Constants::gamma;
constexpr amrex::Real mu = 1.0;
constexpr amrex::Real muk = 1.0;
constexpr amrex::Real k = 1.0;
}}

AMREX_GPU_DEVICE AMREX_FORCE_INLINE
void mms_exact(const amrex::Real x, const amrex::Real y, const amrex::Real z, 
         amrex::Real& rho, amrex::Real& xmom, amrex::Real& ymom, amrex::Real& zmom, amrex::Real& ret) {{
const amrex::Real gamma = mms::gamma;
rho = {cxxcode(rho_a, standard='C++11')};
xmom = {cxxcode(rho_a*u_a, standard='C++11')};
ymom = {cxxcode(rho_a*v_a, standard='C++11')};
zmom = {cxxcode(rho_a*w_a, standard='C++11')};
ret = {cxxcode(ret_a, standard='C++11')};
}}

AMREX_GPU_DEVICE AMREX_FORCE_INLINE
void mms_hydro_source(const amrex::Real x, const amrex::Real y, const amrex::Real z, 
                amrex::Real& rho, amrex::Real& xmom, amrex::Real& ymom, amrex::Real& zmom, amrex::Real& ret) {{
const amrex::Real gamma = mms::gamma;
rho = {cxxcode(hsrc_a[0], standard='C++11')};
xmom = {cxxcode(hsrc_a[1], standard='C++11')};
ymom = {cxxcode(hsrc_a[2], standard='C++11')};
zmom = {cxxcode(hsrc_a[3], standard='C++11')};
ret = {cxxcode(hsrc_a[4], standard='C++11')};
}}

AMREX_GPU_DEVICE AMREX_FORCE_INLINE
void mms_visc_source(const amrex::Real x, const amrex::Real y, const amrex::Real z, 
               amrex::Real& rho, amrex::Real& xmom, amrex::Real& ymom, amrex::Real& zmom, amrex::Real& ret) {{
const amrex::Real gamma = mms::gamma;
const amrex::Real mu = mms::mu;
const amrex::Real muk = mms::muk;
const amrex::Real k = mms::k;
rho = {cxxcode(vsrc_a[0], standard='C++11')};
xmom = {cxxcode(vsrc_a[1], standard='C++11')};
ymom = {cxxcode(vsrc_a[2], standard='C++11')};
zmom = {cxxcode(vsrc_a[3], standard='C++11')};
ret = {cxxcode(vsrc_a[4], standard='C++11')};
}}

#endif"""

with open("mms.H", "w") as file:
  file.write(hpp_content)

print("MMS exact solution and source term written to mms.H")