// This file is automatically generated
// Last update: 19/05/2025 22:50:27
#ifndef MMS_HPP
#define MMS_HPP

#include <cmath>
#include <AMReX_REAL.H>

// Exact MMS solution //
AMREX_GPU_DEVICE AMREX_FORCE_INLINE
void mms_exact(const amrex::Real x, const amrex::Real y, const amrex::Real z, 
         amrex::Real& rho, amrex::Real& u, amrex::Real& v, amrex::Real& w, amrex::Real& p) {
rho = 0.10000000000000001*std::sin(2*M_PI*x) + 0.20000000000000001*std::sin(3*M_PI*z) + 0.14999999999999999*std::cos(2*M_PI*y) + 1.1599999999999999;
u = 27.0*std::sin((3.0/2.0)*M_PI*x) - 17.0*std::cos(0.75*M_PI*y) + 152;
v = 69*std::sin(4*M_PI*x) + 100;
w = 0;
p = -35000*std::sin(2*M_PI*x) + 2500*std::sin((1.0/2.0)*M_PI*z) + 6000*std::cos(4*M_PI*y) + 100000.0;
}

// Source terms for the Euler equations //
AMREX_GPU_DEVICE AMREX_FORCE_INLINE
void mms_source(const amrex::Real x, const amrex::Real y, const amrex::Real z, 
         amrex::Real& Srho, amrex::Real& Srhou, amrex::Real& Srhov, amrex::Real& Srhow, amrex::Real& Srhoe) {
Srho  = -0.29999999999999999*M_PI*(69*std::sin(4*M_PI*x) + 100)*std::sin(2*M_PI*y) + 0.20000000000000001*M_PI*(27.0*std::sin((3.0/2.0)*M_PI*x) - 17.0*std::cos(0.75*M_PI*y) + 152)*std::cos(2*M_PI*x) + 40.5*M_PI*(0.10000000000000001*std::sin(2*M_PI*x) + 0.20000000000000001*std::sin(3*M_PI*z) + 0.14999999999999999*std::cos(2*M_PI*y) + 1.1599999999999999)*std::cos((3.0/2.0)*M_PI*x);
Srhou = -0.29999999999999999*M_PI*(69*std::sin(4*M_PI*x) + 100)*(27.0*std::sin((3.0/2.0)*M_PI*x) - 17.0*std::cos(0.75*M_PI*y) + 152)*std::sin(2*M_PI*y) + 12.75*M_PI*(69*std::sin(4*M_PI*x) + 100)*(0.10000000000000001*std::sin(2*M_PI*x) + 0.20000000000000001*std::sin(3*M_PI*z) + 0.14999999999999999*std::cos(2*M_PI*y) + 1.1599999999999999)*std::sin(0.75*M_PI*y) + 0.20000000000000001*M_PI*std::pow(27.0*std::sin((3.0/2.0)*M_PI*x) - 17.0*std::cos(0.75*M_PI*y) + 152, 2)*std::cos(2*M_PI*x) + 81.0*M_PI*(27.0*std::sin((3.0/2.0)*M_PI*x) - 17.0*std::cos(0.75*M_PI*y) + 152)*(0.10000000000000001*std::sin(2*M_PI*x) + 0.20000000000000001*std::sin(3*M_PI*z) + 0.14999999999999999*std::cos(2*M_PI*y) + 1.1599999999999999)*std::cos((3.0/2.0)*M_PI*x) - 70000*M_PI*std::cos(2*M_PI*x);
Srhov = -0.29999999999999999*M_PI*std::pow(69*std::sin(4*M_PI*x) + 100, 2)*std::sin(2*M_PI*y) + 0.20000000000000001*M_PI*(69*std::sin(4*M_PI*x) + 100)*(27.0*std::sin((3.0/2.0)*M_PI*x) - 17.0*std::cos(0.75*M_PI*y) + 152)*std::cos(2*M_PI*x) + 40.5*M_PI*(69*std::sin(4*M_PI*x) + 100)*(0.10000000000000001*std::sin(2*M_PI*x) + 0.20000000000000001*std::sin(3*M_PI*z) + 0.14999999999999999*std::cos(2*M_PI*y) + 1.1599999999999999)*std::cos((3.0/2.0)*M_PI*x) + 276*M_PI*(27.0*std::sin((3.0/2.0)*M_PI*x) - 17.0*std::cos(0.75*M_PI*y) + 152)*(0.10000000000000001*std::sin(2*M_PI*x) + 0.20000000000000001*std::sin(3*M_PI*z) + 0.14999999999999999*std::cos(2*M_PI*y) + 1.1599999999999999)*std::cos(4*M_PI*x) - 24000*M_PI*std::sin(4*M_PI*y);
Srhow = 1250*M_PI*std::cos((1.0/2.0)*M_PI*z);
Srhoe = (69*std::sin(4*M_PI*x) + 100)*(-0.14999999999999999*M_PI*(std::pow(69*std::sin(4*M_PI*x) + 100, 2) + std::pow(27.0*std::sin((3.0/2.0)*M_PI*x) - 17.0*std::cos(0.75*M_PI*y) + 152, 2))*std::sin(2*M_PI*y) + 25.5*M_PI*(27.0*std::sin((3.0/2.0)*M_PI*x) - 17.0*std::cos(0.75*M_PI*y) + 152)*(0.050000000000000003*std::sin(2*M_PI*x) + 0.10000000000000001*std::sin(3*M_PI*z) + 0.074999999999999997*std::cos(2*M_PI*y) + 0.57999999999999996)*std::sin(0.75*M_PI*y) - 84000.0*M_PI*std::sin(4*M_PI*y)) + ((552*M_PI*(69*std::sin(4*M_PI*x) + 100)*std::cos(4*M_PI*x) + 81.0*M_PI*(27.0*std::sin((3.0/2.0)*M_PI*x) - 17.0*std::cos(0.75*M_PI*y) + 152)*std::cos((3.0/2.0)*M_PI*x))*(0.050000000000000003*std::sin(2*M_PI*x) + 0.10000000000000001*std::sin(3*M_PI*z) + 0.074999999999999997*std::cos(2*M_PI*y) + 0.57999999999999996) + 0.10000000000000001*M_PI*(std::pow(69*std::sin(4*M_PI*x) + 100, 2) + std::pow(27.0*std::sin((3.0/2.0)*M_PI*x) - 17.0*std::cos(0.75*M_PI*y) + 152, 2))*std::cos(2*M_PI*x) - 245000.00000000003*M_PI*std::cos(2*M_PI*x))*(27.0*std::sin((3.0/2.0)*M_PI*x) - 17.0*std::cos(0.75*M_PI*y) + 152) + 40.5*M_PI*((std::pow(69*std::sin(4*M_PI*x) + 100, 2) + std::pow(27.0*std::sin((3.0/2.0)*M_PI*x) - 17.0*std::cos(0.75*M_PI*y) + 152, 2))*(0.050000000000000003*std::sin(2*M_PI*x) + 0.10000000000000001*std::sin(3*M_PI*z) + 0.074999999999999997*std::cos(2*M_PI*y) + 0.57999999999999996) - 122500.00000000001*std::sin(2*M_PI*x) + 8750.0*std::sin((1.0/2.0)*M_PI*z) + 21000.0*std::cos(4*M_PI*y) + 350000.00000000006)*std::cos((3.0/2.0)*M_PI*x);
}


#endif