// This file is automatically generated
// Last update: 20/05/2025 16:49:30
#ifndef MMS_HPP
#define MMS_HPP

#include <cmath>
#include <AMReX_REAL.H>

// Exact MMS solution //
AMREX_GPU_DEVICE AMREX_FORCE_INLINE
void mms_exact(const amrex::Real x, const amrex::Real y, const amrex::Real z, 
         amrex::Real& rho, amrex::Real& u, amrex::Real& v, amrex::Real& w, amrex::Real& p) {
rho = 0.10000000000000001*std::sin(2*M_PI*x) + 0.20000000000000001*std::sin(6*M_PI*z) + 0.14999999999999999*std::cos(2*M_PI*y) + 1.1599999999999999;
u = 27.0*std::sin(4*M_PI*x) - 17.0*std::cos(2*M_PI*y) + 152;
v = 69*std::sin(4*M_PI*x) + 100;
w = 0;
p = -350*std::sin(2*M_PI*x) + 25*std::sin(6*M_PI*z) + 60*std::cos(4*M_PI*y) + 100000.0;
}

// Source terms for the Euler equations //
AMREX_GPU_DEVICE AMREX_FORCE_INLINE
void mms_source(const amrex::Real x, const amrex::Real y, const amrex::Real z, 
         amrex::Real& Srho, amrex::Real& Srhou, amrex::Real& Srhov, amrex::Real& Srhow, amrex::Real& Srhoe) {
Srho  = -0.29999999999999999*M_PI*(69*std::sin(4*M_PI*x) + 100)*std::sin(2*M_PI*y) + 0.20000000000000001*M_PI*(27.0*std::sin(4*M_PI*x) - 17.0*std::cos(2*M_PI*y) + 152)*std::cos(2*M_PI*x) + 108.0*M_PI*(0.10000000000000001*std::sin(2*M_PI*x) + 0.20000000000000001*std::sin(6*M_PI*z) + 0.14999999999999999*std::cos(2*M_PI*y) + 1.1599999999999999)*std::cos(4*M_PI*x);
Srhou = -0.29999999999999999*M_PI*(69*std::sin(4*M_PI*x) + 100)*(27.0*std::sin(4*M_PI*x) - 17.0*std::cos(2*M_PI*y) + 152)*std::sin(2*M_PI*y) + 34.0*M_PI*(69*std::sin(4*M_PI*x) + 100)*(0.10000000000000001*std::sin(2*M_PI*x) + 0.20000000000000001*std::sin(6*M_PI*z) + 0.14999999999999999*std::cos(2*M_PI*y) + 1.1599999999999999)*std::sin(2*M_PI*y) + 0.20000000000000001*M_PI*std::pow(27.0*std::sin(4*M_PI*x) - 17.0*std::cos(2*M_PI*y) + 152, 2)*std::cos(2*M_PI*x) + 216.0*M_PI*(27.0*std::sin(4*M_PI*x) - 17.0*std::cos(2*M_PI*y) + 152)*(0.10000000000000001*std::sin(2*M_PI*x) + 0.20000000000000001*std::sin(6*M_PI*z) + 0.14999999999999999*std::cos(2*M_PI*y) + 1.1599999999999999)*std::cos(4*M_PI*x) - 700*M_PI*std::cos(2*M_PI*x);
Srhov = -0.29999999999999999*M_PI*std::pow(69*std::sin(4*M_PI*x) + 100, 2)*std::sin(2*M_PI*y) + 0.20000000000000001*M_PI*(69*std::sin(4*M_PI*x) + 100)*(27.0*std::sin(4*M_PI*x) - 17.0*std::cos(2*M_PI*y) + 152)*std::cos(2*M_PI*x) + 108.0*M_PI*(69*std::sin(4*M_PI*x) + 100)*(0.10000000000000001*std::sin(2*M_PI*x) + 0.20000000000000001*std::sin(6*M_PI*z) + 0.14999999999999999*std::cos(2*M_PI*y) + 1.1599999999999999)*std::cos(4*M_PI*x) + 276*M_PI*(27.0*std::sin(4*M_PI*x) - 17.0*std::cos(2*M_PI*y) + 152)*(0.10000000000000001*std::sin(2*M_PI*x) + 0.20000000000000001*std::sin(6*M_PI*z) + 0.14999999999999999*std::cos(2*M_PI*y) + 1.1599999999999999)*std::cos(4*M_PI*x) - 240*M_PI*std::sin(4*M_PI*y);
Srhow = 150*M_PI*std::cos(6*M_PI*z);
Srhoe = (69*std::sin(4*M_PI*x) + 100)*(-0.14999999999999999*M_PI*(std::pow(69*std::sin(4*M_PI*x) + 100, 2) + std::pow(27.0*std::sin(4*M_PI*x) - 17.0*std::cos(2*M_PI*y) + 152, 2))*std::sin(2*M_PI*y) + 68.0*M_PI*(27.0*std::sin(4*M_PI*x) - 17.0*std::cos(2*M_PI*y) + 152)*(0.050000000000000003*std::sin(2*M_PI*x) + 0.10000000000000001*std::sin(6*M_PI*z) + 0.074999999999999997*std::cos(2*M_PI*y) + 0.57999999999999996)*std::sin(2*M_PI*y) - 840.00000000000011*M_PI*std::sin(4*M_PI*y)) + ((552*M_PI*(69*std::sin(4*M_PI*x) + 100)*std::cos(4*M_PI*x) + 216.0*M_PI*(27.0*std::sin(4*M_PI*x) - 17.0*std::cos(2*M_PI*y) + 152)*std::cos(4*M_PI*x))*(0.050000000000000003*std::sin(2*M_PI*x) + 0.10000000000000001*std::sin(6*M_PI*z) + 0.074999999999999997*std::cos(2*M_PI*y) + 0.57999999999999996) + 0.10000000000000001*M_PI*(std::pow(69*std::sin(4*M_PI*x) + 100, 2) + std::pow(27.0*std::sin(4*M_PI*x) - 17.0*std::cos(2*M_PI*y) + 152, 2))*std::cos(2*M_PI*x) - 2450.0*M_PI*std::cos(2*M_PI*x))*(27.0*std::sin(4*M_PI*x) - 17.0*std::cos(2*M_PI*y) + 152) + 108.0*M_PI*((std::pow(69*std::sin(4*M_PI*x) + 100, 2) + std::pow(27.0*std::sin(4*M_PI*x) - 17.0*std::cos(2*M_PI*y) + 152, 2))*(0.050000000000000003*std::sin(2*M_PI*x) + 0.10000000000000001*std::sin(6*M_PI*z) + 0.074999999999999997*std::cos(2*M_PI*y) + 0.57999999999999996) - 1225.0*std::sin(2*M_PI*x) + 87.500000000000014*std::sin(6*M_PI*z) + 210.00000000000003*std::cos(4*M_PI*y) + 350000.00000000006)*std::cos(4*M_PI*x);
}


#endif