TINY_PROFILE = FALSE
DEBUG = TRUE
DIM=3
USE_MPI = TRUE
USE_OMP = FALSE

include ./Make.package
include ../src/Make.CNS
INCLUDE_LOCATIONS += ../lib/install/boost/include
LIBRARY_LOCATIONS += ../lib/install/boost/lib
#LIBRARIES += -lboost

INCLUDE_LOCATIONS += ../lib/install/cgal/include
LIBRARY_LOCATIONS += ../lib/install/cgal/lib/cmake/CGAL
LIBRARIES += -lgmp
