// This file is automatically generated
  // Last update: 30/06/2025 18:37:10
  #ifndef MMS_HPP
  #define MMS_HPP

  #include <cmath>
  #include <AMReX_REAL.H>

  // Exact MMS solution //
  AMREX_GPU_DEVICE AMREX_FORCE_INLINE
  void mms_exact(const amrex::Real x, const amrex::Real y, const amrex::Real z, 
         amrex::Real& rho, amrex::Real& u, amrex::Real& v, amrex::Real& w, amrex::Real& p,
         const amrex::Real dx, const amrex::Real dy, const amrex::Real dz) {
  rho = -(-1.0/2.0*dx + x)*(-1.1599999999999999*dz*(-1.0/2.0*dy + y) + 1.1599999999999999*dz*((1.0/2.0)*dy + y)) + ((1.0/2.0)*dx + x)*(-1.1599999999999999*dz*(-1.0/2.0*dy + y) + 1.1599999999999999*dz*((1.0/2.0)*dy + y));
  u = -(-1.0/2.0*dx + x)*(-((1.0/2.0)*dz - z)*(-76.0*dy + 152.0*y - 7.6000000000000005*std::cos(M_PI*(-dy + 2*y))/M_PI) + ((1.0/2.0)*dz - z)*(76.0*dy + 152.0*y - 7.6000000000000005*std::cos(M_PI*(dy + 2*y))/M_PI) - ((1.0/2.0)*dz + z)*(-76.0*dy + 152.0*y - 7.6000000000000005*std::cos(M_PI*(-dy + 2*y))/M_PI) + ((1.0/2.0)*dz + z)*(76.0*dy + 152.0*y - 7.6000000000000005*std::cos(M_PI*(dy + 2*y))/M_PI)) + ((1.0/2.0)*dx + x)*(-((1.0/2.0)*dz - z)*(-76.0*dy + 152.0*y - 7.6000000000000005*std::cos(M_PI*(-dy + 2*y))/M_PI) + ((1.0/2.0)*dz - z)*(76.0*dy + 152.0*y - 7.6000000000000005*std::cos(M_PI*(dy + 2*y))/M_PI) - ((1.0/2.0)*dz + z)*(-76.0*dy + 152.0*y - 7.6000000000000005*std::cos(M_PI*(-dy + 2*y))/M_PI) + ((1.0/2.0)*dz + z)*(76.0*dy + 152.0*y - 7.6000000000000005*std::cos(M_PI*(dy + 2*y))/M_PI));
  v = 0;
  w = 0;
  p = -(-1.0/2.0*dx + x)*(-1914331.4285714282*dz*(-1.0/2.0*dy + y) + 1914331.4285714282*dz*((1.0/2.0)*dy + y)) + ((1.0/2.0)*dx + x)*(-1914331.4285714282*dz*(-1.0/2.0*dy + y) + 1914331.4285714282*dz*((1.0/2.0)*dy + y));
 
  rho /= (dx*dy*dz);
  u   /= (dx*dy*dz);
  v   /= (dx*dy*dz);  
  w   /= (dx*dy*dz);
  p   /= (dx*dy*dz);

  }

  // Source terms for the Euler equations //
  AMREX_GPU_DEVICE AMREX_FORCE_INLINE
  void mms_source(const amrex::Real x, const amrex::Real y, const amrex::Real z, 
         amrex::Real& Srho, amrex::Real& Srhou, amrex::Real& Srhov, amrex::Real& Srhow, amrex::Real& Srhoe,
         const amrex::Real dx, const amrex::Real dy, const amrex::Real dz) {
  Srho  = 0;
  Srhou = -(-1.0/2.0*dx + x)*(-5360.1280000000006*M_PI*(-1.0/2.0*dz + z)*std::cos(M_PI*(-dy + 2*y)) + 5360.1280000000006*M_PI*(-1.0/2.0*dz + z)*std::cos(M_PI*(dy + 2*y)) + 5360.1280000000006*M_PI*((1.0/2.0)*dz + z)*std::cos(M_PI*(-dy + 2*y)) - 5360.1280000000006*M_PI*((1.0/2.0)*dz + z)*std::cos(M_PI*(dy + 2*y))) + ((1.0/2.0)*dx + x)*(-5360.1280000000006*M_PI*(-1.0/2.0*dz + z)*std::cos(M_PI*(-dy + 2*y)) + 5360.1280000000006*M_PI*(-1.0/2.0*dz + z)*std::cos(M_PI*(dy + 2*y)) + 5360.1280000000006*M_PI*((1.0/2.0)*dz + z)*std::cos(M_PI*(-dy + 2*y)) - 5360.1280000000006*M_PI*((1.0/2.0)*dz + z)*std::cos(M_PI*(dy + 2*y)));
  Srhov = 0;
  Srhow = 0;
  Srhoe = -(-1.0/2.0*dx + x)*(-((1.0/2.0)*dz - z)*(-81473.945600000021*M_PI*std::sin(M_PI*(-dy + 2*y))*std::cos(M_PI*(-dy + 2*y)) - 814739.45600000012*M_PI*std::cos(M_PI*(-dy + 2*y))) + ((1.0/2.0)*dz - z)*(-81473.945600000021*M_PI*std::sin(M_PI*(dy + 2*y))*std::cos(M_PI*(dy + 2*y)) - 814739.45600000012*M_PI*std::cos(M_PI*(dy + 2*y))) - ((1.0/2.0)*dz + z)*(-81473.945600000021*M_PI*std::sin(M_PI*(-dy + 2*y))*std::cos(M_PI*(-dy + 2*y)) - 814739.45600000012*M_PI*std::cos(M_PI*(-dy + 2*y))) + ((1.0/2.0)*dz + z)*(-81473.945600000021*M_PI*std::sin(M_PI*(dy + 2*y))*std::cos(M_PI*(dy + 2*y)) - 814739.45600000012*M_PI*std::cos(M_PI*(dy + 2*y)))) + ((1.0/2.0)*dx + x)*(-((1.0/2.0)*dz - z)*(-81473.945600000021*M_PI*std::sin(M_PI*(-dy + 2*y))*std::cos(M_PI*(-dy + 2*y)) - 814739.45600000012*M_PI*std::cos(M_PI*(-dy + 2*y))) + ((1.0/2.0)*dz - z)*(-81473.945600000021*M_PI*std::sin(M_PI*(dy + 2*y))*std::cos(M_PI*(dy + 2*y)) - 814739.45600000012*M_PI*std::cos(M_PI*(dy + 2*y))) - ((1.0/2.0)*dz + z)*(-81473.945600000021*M_PI*std::sin(M_PI*(-dy + 2*y))*std::cos(M_PI*(-dy + 2*y)) - 814739.45600000012*M_PI*std::cos(M_PI*(-dy + 2*y))) + ((1.0/2.0)*dz + z)*(-81473.945600000021*M_PI*std::sin(M_PI*(dy + 2*y))*std::cos(M_PI*(dy + 2*y)) - 814739.45600000012*M_PI*std::cos(M_PI*(dy + 2*y))));

  Srho  /= (dx*dy*dz);
  Srhou /= (dx*dy*dz);
  Srhov /= (dx*dy*dz);
  Srhow /= (dx*dy*dz);
  Srhoe /= (dx*dy*dz);

  }
  #endif