TINY_PROFILE 	= TRUE
DEBUG   	= FALSE
PRECISION = DOUBLE # DOUBLE or FLOAT
DIM     	= 3
COMP 		  = gcc
CXXSTD    = c++17
USE_CUDA 	= TRUE 
USE_MPI 	= TRUE
USE_OMP 	= FALSE
USE_GPIBM	= FALSE
AMREX_NO_PROBINIT=TRUE
CUDA_ARCH=8.0

AMR_SOLVER = $(abspath ../../)
AMREX_HOME = $(abspath ../../lib/amrex)

CEXE_headers += prob.h
include $(AMR_SOLVER)/src/Make.CNS