import pyvista as pv
import argparse
import sys
import os

def read_cerisse_vtp(filename):
    """
    Reads a .vtp file generated by Cerisse and prints information about it.
    """
    if not os.path.exists(filename):
        print(f"Error: File '{filename}' not found.")
        sys.exit(1)

    try:
        # Load the .vtp file
        mesh = pv.read(filename)
    except Exception as e:
        print(f"Error reading file: {e}")
        sys.exit(1)

    print(f"Successfully loaded: {filename}")
    print("-" * 40)
    
    # Mesh statistics
    print(f"Number of Points: {mesh.n_points}")
    print(f"Number of Cells:  {mesh.n_cells}")
    
    # Check for Cell Data (Cerisse writes data to CellData)
    if mesh.cell_data:
        print("\nAvailable Cell Data (Scalars):")
        for name in mesh.cell_data:
            data = mesh.cell_data[name]
            print(f" - {name:<15}: Min = {data.min():.4e}, Max = {data.max():.4e}")
    else:
        print("\nNo Cell Data found.")

    # Check for Point Data (just in case)
    if mesh.point_data:
        print("\nAvailable Point Data:")
        for name in mesh.point_data:
            data = mesh.point_data[name]
            print(f" - {name:<15}: Min = {data.min():.4e}, Max = {data.max():.4e}")

    print("-" * 40)
    
    return mesh

def plot_mesh(mesh, scalar_field=None):
    """
    Plots the mesh using PyVista.
    """
    print("\nLaunching plotter...")
    
    # Set a default scalar field if none provided but data exists
    if scalar_field is None and mesh.cell_data:
        scalar_field = list(mesh.cell_data.keys())[0]
        print(f"No scalar field specified, defaulting to '{scalar_field}'")
    
    try:
        mesh.plot(scalars=scalar_field, show_edges=True, cmap="jet")
    except Exception as e:
        print(f"Error plotting mesh: {e}")

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Read and inspect Cerisse output .vtp files.")
    parser.add_argument("filename", help="Path to the .vtp file")
    parser.add_argument("--plot", action="store_true", help="Visualize the mesh")
    parser.add_argument("--field", type=str, help="Scalar field to plot (e.g., Pressure, Temperature)", default=None)

    args = parser.parse_args()

    mesh = read_cerisse_vtp(args.filename)

    if args.plot:
        plot_mesh(mesh, args.field)
