"""
vis_vtp_3d.py

Description:
    This script reads and inspects .vtp (VTK PolyData) files generated by the Cerisse solver.
    It prints mesh statistics (number of points, cells) and lists available scalar fields
    (e.g., Pressure, Temperature) with their min/max values.
    It also provides a basic 3D visualization using PyVista.
    
    Supports visualizing multiple files side-by-side.

Usage:
    1. Inspect file information only:
       python vis_vtp_3d.py path/to/file.vtp

    2. Visualize a single file with a specific field:
       python vis_vtp_3d.py path/to/file.vtp --plot --field Pressure

    3. Compare multiple files side-by-side:
       python vis_vtp_3d.py file1.vtp file2.vtp --plot --field Pressure

Dependencies:
    - pyvista
    - numpy
"""

import pyvista as pv
import argparse
import sys
import os
import math

def read_cerisse_vtp(filename, print_info=True):
    """
    Reads a .vtp file generated by Cerisse and prints information about it.
    """
    if not os.path.exists(filename):
        print(f"Error: File '{filename}' not found.")
        return None

    try:
        # Load the .vtp file
        mesh = pv.read(filename)
    except Exception as e:
        print(f"Error reading file {filename}: {e}")
        return None

    if print_info:
        print(f"Successfully loaded: {filename}")
        print("-" * 40)
        
        # Mesh statistics
        print(f"Number of Points: {mesh.n_points}")
        print(f"Number of Cells:  {mesh.n_cells}")
        
        # Check for Cell Data (Cerisse writes data to CellData)
        if mesh.cell_data:
            print("\nAvailable Cell Data (Scalars):")
            for name in mesh.cell_data:
                data = mesh.cell_data[name]
                print(f" - {name:<15}: Min = {data.min():.4e}, Max = {data.max():.4e}")
        else:
            print("\nNo Cell Data found.")

        # Check for Point Data (just in case)
        if mesh.point_data:
            print("\nAvailable Point Data:")
            for name in mesh.point_data:
                data = mesh.point_data[name]
                print(f" - {name:<15}: Min = {data.min():.4e}, Max = {data.max():.4e}")

        print("-" * 40)
    
    return mesh

def plot_meshes(meshes, filenames, scalar_fields=None):
    """
    Plots multiple meshes using PyVista in a grid layout.
    """
    if not meshes: return

    # Prepare list of (mesh, filename, field) to plot
    plot_items = []
    for mesh, filename in zip(meshes, filenames):
        if not scalar_fields:
            plot_items.append((mesh.copy(), filename, None))
        else:
            for field in scalar_fields:
                plot_items.append((mesh.copy(), filename, field))

    n_items = len(plot_items)
    print(f"\nLaunching plotter for {n_items} view(s)...")
    
    # Calculate grid dimensions
    n_cols = math.ceil(math.sqrt(n_items))
    n_rows = math.ceil(n_items / n_cols)
    
    plotter = pv.Plotter(shape=(n_rows, n_cols))

    for i, (mesh, filename, req_field) in enumerate(plot_items):
        row = i // n_cols
        col = i % n_cols
        plotter.subplot(row, col)
        
        # Determine field to plot for this mesh
        current_field = req_field
        if current_field is None:
            if mesh.cell_data:
                current_field = list(mesh.cell_data.keys())[0]
            elif mesh.point_data:
                current_field = list(mesh.point_data.keys())[0]
        
        # Add text with larger font and background for better visibility
        plotter.add_text(f"{os.path.basename(filename)}\n{current_field}", font_size=12)
        
        try:
            plotter.add_mesh(mesh, scalars=current_field, show_edges=True, cmap="jet")
            plotter.show_grid()
            # Set camera to view XY plane by default (Z-axis pointing towards viewer)
            plotter.view_xy() 
        except Exception as e:
            print(f"Error plotting mesh {filename}: {e}")

    plotter.link_views()  # Link cameras
    plotter.show()

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Read and inspect Cerisse output .vtp files.")
    parser.add_argument("filenames", nargs='+', help="Path to the .vtp file(s)")
    parser.add_argument("--plot", action="store_true", help="Visualize the mesh")
    parser.add_argument("--field", nargs='+', type=str, help="Scalar field(s) to plot (e.g., Pressure Temperature)", default=None)

    args = parser.parse_args()

    meshes = []
    valid_filenames = []
    
    # Read all files and print info
    for filename in args.filenames:
        # Always print info
        mesh = read_cerisse_vtp(filename, print_info=True)
        if mesh:
            meshes.append(mesh)
            valid_filenames.append(filename)

    if args.plot and meshes:
        plot_meshes(meshes, valid_filenames, args.field)
