# AMReX
DIM = 3
COMP = gnu
PRECISION = DOUBLE

# Profiling
PROFILE = FALSE
TINY_PROFILE = FALSE
COMM_PROFILE = FALSE
TRACE_PROFILE = FALSE
MEM_PROFILE = FALSE
USE_GPROF = FALSE

# Performance
USE_MPI = FALSE
USE_OMP = FALSE
USE_CUDA = FALSE
USE_HIP = FALSE
USE_SYCL = FALSE

# Debugging
DEBUG = TRUE
FSANITIZER = FALSE
THREAD_SANITIZER = FALSE
EXTRA_DEBUG = TRUE


# PelePhysics
Eos_Model := Fuego
Transport_Model := Simple
Chemistry_Model := air

# CNS
USE_EB = TRUE

# GNU Make
include ./Make.package
include ../../Source/Make.CNS
